# Generated by Django 5.1.3 on 2024-11-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='descreption',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
